### ISSUE TITLE
Create component for numeric input & validation

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#595]
As this issue is written, code dealing with numeric input and validation (checking NaN, turning borders red, etc.) is repeated in multiple places.  Investigate the feasibility & desirability of isolating this code in a single place.  Implement as appropriate.

**Comment by 1fifoto** [comment]
Add valueMin and valueMax as props. Add checking to insure value is "within" valueMin and valueMax. If not "within" then display red border and maybe an error message or tooltip.

**Comment by grumpyinca** [comment]
Testing results.

Very odd.  Working in Advanced View, I change values. Run Search.  Nothing unexpected.  Then as I am scrolling up and down over several seconds with no intended input (possibly a stray click when I run off from the scroll bar?) the screen abruptly goes all white.  The console displays:
```
[Violation] 'input' handler took 214ms
[Violation] 'input' handler took 255ms
[Violation] 'input' handler took 199ms
react-dom.development.js:175 [Violation] 'click' handler took 185ms
[Violation] 'click' handler took 375ms
logUsage.js:12 Fetch finished loading: POST "http://localhost:3000/api/v1/usage_log".
logIt @ logUsage.js:12
flushBuffer @ logUsage.js:54
logUsage @ logUsage.js:77
onSearchButton @ ResultTable.js:46
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:391
executeDispatchesInOrder @ react-dom.development.js:416
executeDispatchesAndRelease @ react-dom.development.js:3301
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3310
forEachAccumulated @ react-dom.development.js:3282
runEventsInBatch @ react-dom.development.js:3327
runExtractedPluginEventsInBatch @ react-dom.development.js:3537
handleTopLevel @ react-dom.development.js:3581
batchedEventUpdates$1 @ react-dom.development.js:21729
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3591
attemptToDispatchEvent @ react-dom.development.js:4311
dispatchEvent @ react-dom.development.js:4232
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11077
discreteUpdates$1 @ react-dom.development.js:21746
discreteUpdates @ react-dom.development.js:811
dispatchDiscreteEvent @ react-dom.development.js:4211
logUsage.js:12 Fetch finished loading: POST "http://localhost:3000/api/v1/usage_log".
logIt @ logUsage.js:12
logUsage @ logUsage.js:78
onSearchButton @ ResultTable.js:46
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:391
executeDispatchesInOrder @ react-dom.development.js:416
executeDispatchesAndRelease @ react-dom.development.js:3301
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3310
forEachAccumulated @ react-dom.development.js:3282
runEventsInBatch @ react-dom.development.js:3327
runExtractedPluginEventsInBatch @ react-dom.development.js:3537
handleTopLevel @ react-dom.development.js:3581
batchedEventUpdates$1 @ react-dom.development.js:21729
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3591
attemptToDispatchEvent @ react-dom.development.js:4311
dispatchEvent @ react-dom.development.js:4232
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11077
discreteUpdates$1 @ react-dom.development.js:21746
discreteUpdates @ react-dom.development.js:811
dispatchDiscreteEvent @ react-dom.development.js:4211
6Fetch finished loading: GET "<URL>".
logUsage.js:12 Fetch finished loading: POST "http://localhost:3000/api/v1/usage_log".
logIt @ logUsage.js:12
logUsage @ logUsage.js:78
(anonymous) @ FileOpen.js:113
Promise.then (async)
getDesign @ FileOpen.js:105
onOpen @ FileOpen.js:205
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:391
executeDispatchesInOrder @ react-dom.development.js:413
executeDispatchesAndRelease @ react-dom.development.js:3301
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3310
forEachAccumulated @ react-dom.development.js:3282
runEventsInBatch @ react-dom.development.js:3327
runExtractedPluginEventsInBatch @ react-dom.development.js:3537
handleTopLevel @ react-dom.development.js:3581
batchedEventUpdates$1 @ react-dom.development.js:21729
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3591
attemptToDispatchEvent @ react-dom.development.js:4311
dispatchEvent @ react-dom.development.js:4232
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11077
discreteUpdates$1 @ react-dom.development.js:21746
discreteUpdates @ react-dom.development.js:811
dispatchDiscreteEvent @ react-dom.development.js:4211
Overlay.js:78 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'className')
    at Object.children (Overlay.js:78:1)
    at Overlay.js:83:1
    at renderWithHooks (react-dom.development.js:14797:1)
    at updateForwardRef (react-dom.development.js:16769:1)
    at beginWork (react-dom.development.js:18538:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238:1)
    at invokeGuardedCallback (react-dom.development.js:291:1)
    at beginWork$1 (react-dom.development.js:23055:1)
    at performUnitOfWork (react-dom.development.js:22022:1)
    at workLoopSync (react-dom.development.js:21995:1)
    at performSyncWorkOnRoot (react-dom.development.js:21613:1)
    at react-dom.development.js:11131:1
    at unstable_runWithPriority (scheduler.development.js:659:1)
    at runWithPriority$1 (react-dom.development.js:11077:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11126:1)
    at flushSyncCallbackQueue (react-dom.development.js:11114:1)
    at batchedEventUpdates$1 (react-dom.development.js:21735:1)
    at batchedEventUpdates (react-dom.development.js:798:1)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js:3591:1)
    at attemptToDispatchEvent (react-dom.development.js:4311:1)
    at dispatchEvent (react-dom.development.js:4232:1)
    at unstable_runWithPriority (scheduler.development.js:659:1)
    at dispatchUserBlockingUpdate (react-dom.development.js:4215:1)
(anonymous) @ Overlay.js:78
(anonymous) @ Overlay.js:83
renderWithHooks @ react-dom.development.js:14797
updateForwardRef @ react-dom.development.js:16769
beginWork @ react-dom.development.js:18538
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
beginWork$1 @ react-dom.development.js:23055
performUnitOfWork @ react-dom.development.js:22022
workLoopSync @ react-dom.development.js:21995
performSyncWorkOnRoot @ react-dom.development.js:21613
(anonymous) @ react-dom.development.js:11131
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11077
flushSyncCallbackQueueImpl @ react-dom.development.js:11126
flushSyncCallbackQueue @ react-dom.development.js:11114
batchedEventUpdates$1 @ react-dom.development.js:21735
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3591
attemptToDispatchEvent @ react-dom.development.js:4311
dispatchEvent @ react-dom.development.js:4232
unstable_runWithPriority @ scheduler.development.js:659
dispatchUserBlockingUpdate @ react-dom.development.js:4215
index.js:1437 
        
       The above error occurred in the <Overlay> component:
    in Overlay (created by Overlay)
    in Overlay (created by OverlayTrigger)
    in OverlayTrigger (at NameValueUnitsRowDependentVariable.js:47)
    in tbody (at NameValueUnitsRowDependentVariable.js:46)
    in NameValueUnitsRowDependentVariable (created by Connect(NameValueUnitsRowDependentVariable))
    in Connect(NameValueUnitsRowDependentVariable) (at NameValueUnitsTable.js:19)
    in table (created by ForwardRef)
    in ForwardRef (at NameValueUnitsTable.js:15)
    in NameValueUnitsTable (created by Connect(NameValueUnitsTable))
    in Connect(NameValueUnitsTable) (at DesignTable.js:20)
    in div (created by Row)
    in Row (at DesignTable.js:19)
    in DesignTable (created by Connect(DesignTable))
    in Connect(DesignTable) (at view.js:10)
    in div (at MainPage.js:192)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    in TabPane (created by Tabs)
    in div (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in TabContainer (created by Tabs)
    in Tabs (at MainPage.js:189)
    in div (created by Container)
    in Container (at MainPage.js:187)
    in MainPage (created by Connect(MainPage))
    in Connect(MainPage) (created by withOktaAuth_Connect(MainPage))
    in withOktaAuth_Connect(MainPage) (created by Context.Consumer)
    in withRouter(withOktaAuth_Connect(MainPage)) (created by Context.Consumer)
    in Route (at Routes.js:139)
    in Security (at Routes.js:137)
    in Routes (created by Connect(Routes))
    in Connect(Routes) (created by Context.Consumer)
    in withRouter(Connect(Routes)) (at src/index.js:55)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:54)
    in Provider (at src/index.js:53)
    in div (at src/index.js:47)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1437
logCapturedError @ react-dom.development.js:19411
logError @ react-dom.development.js:19447
update.callback @ react-dom.development.js:20563
callCallback @ react-dom.development.js:12531
commitUpdateQueue @ react-dom.development.js:12554
commitLifeCycles @ react-dom.development.js:19757
commitLayoutEffects @ react-dom.development.js:22662
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
commitRootImpl @ react-dom.development.js:22404
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11077
commitRoot @ react-dom.development.js:22246
finishSyncRender @ react-dom.development.js:21663
performSyncWorkOnRoot @ react-dom.development.js:21649
(anonymous) @ react-dom.development.js:11131
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11077
flushSyncCallbackQueueImpl @ react-dom.development.js:11126
flushSyncCallbackQueue @ react-dom.development.js:11114
batchedEventUpdates$1 @ react-dom.development.js:21735
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3591
attemptToDispatchEvent @ react-dom.development.js:4311
dispatchEvent @ react-dom.development.js:4232
unstable_runWithPriority @ scheduler.development.js:659
dispatchUserBlockingUpdate @ react-dom.development.js:4215
Overlay.js:78 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'className')
    at Object.children (Overlay.js:78:1)
    at Overlay.js:83:1
    at renderWithHooks (react-dom.development.js:14797:1)
    at updateForwardRef (react-dom.development.js:16769:1)
    at beginWork (react-dom.development.js:18538:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238:1)
    at invokeGuardedCallback (react-dom.development.js:291:1)
    at beginWork$1 (react-dom.development.js:23055:1)
    at performUnitOfWork (react-dom.development.js:22022:1)
    at workLoopSync (react-dom.development.js:21995:1)
    at performSyncWorkOnRoot (react-dom.development.js:21613:1)
    at react-dom.development.js:11131:1
    at unstable_runWithPriority (scheduler.development.js:659:1)
    at runWithPriority$1 (react-dom.development.js:11077:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11126:1)
    at flushSyncCallbackQueue (react-dom.development.js:11114:1)
    at batchedEventUpdates$1 (react-dom.development.js:21735:1)
    at batchedEventUpdates (react-dom.development.js:798:1)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js:3591:1)
    at attemptToDispatchEvent (react-dom.development.js:4311:1)
    at dispatchEvent (react-dom.development.js:4232:1)
    at unstable_runWithPriority (scheduler.development.js:659:1)
    at dispatchUserBlockingUpdate (react-dom.development.js:4215:1)
(anonymous) @ Overlay.js:78
(anonymous) @ Overlay.js:83
renderWithHooks @ react-dom.development.js:14797
updateForwardRef @ react-dom.development.js:16769
beginWork @ react-dom.development.js:18538
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
beginWork$1 @ react-dom.development.js:23055
performUnitOfWork @ react-dom.development.js:22022
workLoopSync @ react-dom.development.js:21995
performSyncWorkOnRoot @ react-dom.development.js:21613
(anonymous) @ react-dom.development.js:11131
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11077
flushSyncCallbackQueueImpl @ react-dom.development.js:11126
flushSyncCallbackQueue @ react-dom.development.js:11114
batchedEventUpdates$1 @ react-dom.development.js:21735
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3591
attemptToDispatchEvent @ react-dom.development.js:4311
dispatchEvent @ react-dom.development.js:4232
unstable_runWithPriority @ scheduler.development.js:659
dispatchUserBlockingUpdate @ react-dom.development.js:4215
[Violation] 'mouseover' handler took 189ms
```
While this has happened multiple times, I am not yet able to find a sequence to make it happen on command.

**Comment by 1fifoto** [comment]
There was a spurious <OverlayTrigger...> in NameValueUnitsRowDependentVariable that shouldn't have been there. I have removed it and I don't see the error happening any more. Can you retry to see if it still occurs for you when you have time.

**Comment by grumpyinca** [comment]
Testing results:

I was able to produce the following error message in the development environment with the sequence:

1. Reload
2. File : Open Extension Startup  (it migrates v5 to v6)
3. Click in field for Force_1 MIN; observe "Functionally Determined Constraint Level (FDCL) - Set Force_1 Min Constraint" modal.
4. Click "Enter button"; observe white screen with error message:

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
▶ 4 stack frames were collapsed.
FormControlTypeNumber.componentDidUpdate
C:/Users/Mike/git/odop/client/src/components/FormControlTypeNumber.js:39
  36 |         if (prevProps.value !== this.props.value) {
  37 | //            console.log('In FormControlTypeNumber.componentDidUpdate prevProps.value=',prevProps.value,'props.value=',this.props.value);
  38 |             var value = parseFloat(this.props.value);
> 39 |             this.setState({
  40 |                 value: value,
  41 |                 valueString: value.toString(), // Update the display
  42 |             }); 
```
Note:  Originally found the problem with the FDCL modal sequence:
Double-click Value field; observe highlights "6"
Hit Delete key; observe red border (good!)
enter keystrokes: ".6e1" observe that red border disappears  (good!)
Click "Enter button"; observe white screen with error message

**Comment by grumpyinca** [comment]
More testing results:

In v4.1, hovering over a FDCL produces a tooltip.  In branch 595, the tooltip is mostly suppressed (except for brief flash).

**Comment by grumpyinca** [comment]
More testing results:

Cannot supply a value for a fixed dependent variable.

**Comment by 1fifoto** [comment]
Fixed the above three problems:

* Force_1 MIN; observe "Functionally Determined Constraint Level (FDCL) - Set Force_1 Min Constraint" > "Enter button" > observe white screen
* Hovering over a FDCL produces NO tooltip
* Cannot supply a value for a fixed dependent variable.

**Comment by 1fifoto** [comment]
Set fixed dependent variable. Enter dependent constraint min value. The dependent constraint max value should track and change too.

**Comment by grumpyinca** [comment]
More testing results: 

This one is likely a different symptom (or variation) of the "NaN not parsed" issue noted above.  
To re-create:
1. Load extension spring Startup
2. Clear console log messages
3. Set Force_1 to any value less than Initial_Tension (5 is a good number)
4. Observe that the Force_1 MIN constraint disappears (appears disabled) but the tooltip suggests that it is now a non-FDCL value of 6.
5. Observe that the console log displays:  
  "react-dom.development.js:2069 
  The specified value "NaN" cannot be parsed, or is out of range.".

**Comment by grumpyinca** [comment]
Updated comment of January 22 such that the four entries are enumerated as A, B, C, & D.

Confirmed that entries A & B can be reproduced in the current state of branch #595.

Improved wording of entry "A.".

It appears that entry "B." is most serious and perhaps should be addressed first.  Once it is resolved, it is possible that "A.6" will change.

**Comment by 1fifoto** [comment]
Fixed the above "A few more problems" (reported on Jan 22, 2022 11:56 AM CST)

1. Set fixed dependent variable. Enter dependent constraint min value. The dependent constraint max value should track and change too.
2. "NaN" not parsed console warning message. This does not appear in 'master' branch, so I think this is specific to 595.

Fixed the above "More testing results"  (reported on Jan 22, 2022 9:30 PM CST)

A. This one is likely a different symptom (or variation) of the "NaN not parsed" issue noted above...
B. Either this one is new or somehow escaped previous testing...

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by 1fifoto** [comment]
Fixed "Maximum update depth exceeded" in branch $595, which is the first entry in https://github.com/thegrumpys/odop/issues/590#issuecomment-1019686789

Fixed "Maximum update depth exceeded" in branch #595, which is in https://github.com/thegrumpys/odop/issues/590#issuecomment-1037761161

**Comment by 1fifoto** [comment]
New problem: Attempts to change constraint levels (Advanced & Calculator views; Wire_Dia & other variables) are immediately reset to the previous values.

**Comment by 1fifoto** [comment]
Fixed, merged into master, closing one more time

**Comment by grumpyinca** [comment]
Newly discovered problem:

When disabling a constraint, the existing constraint level remains visible.  In v4.1 and earlier, the constraint level is blanked out.

**Comment by 1fifoto** [comment]
Repaired "When disabling a constraint, the existing constraint level remains visible. In v4.1 and earlier, the constraint level is blanked out.". Merged into master, closing

**Comment by grumpyinca** [comment]
Newly discovered problem:

In Advanced View, Dependent Variables are not displayed.  In Calculator View, calculated results are not displayed.

**Comment by 1fifoto** [comment]
Oops, my goof, thanks. Previously I tried a simple change to hide the text if the component was disabled, but that was wrong, wrong, wrong. So I had to add a new disabledText property instead. Repaired "In Advanced View, Dependent Variables are not displayed. In Calculator View, calculated results are not displayed." Please keep beating on this component. Merged into master, closing

**Comment by grumpyinca** [comment]
Now for something really weird.

Make a change to an Independent Variable (or Search or Seek) and most (but not all!) Dependent Variables fail to update to reflect the change.  With PCyl and Solid, only the last DV seems to get updated properly.  With compression spring, a constrained DV in the middle updates properly.

I suggest using PCyl to keep the situation simple.  Also, I have found it helpful to have a side-by-side comparison with the same changes in the production system.  I have a hunch that this is yet another React stale data problem.

**Comment by 1fifoto** [comment]
It was learned as we went through the example above, that Mike would change the Coils_T value by selecting the field and overwriting the '10 value's '0' to be '2' to make '12'. Whereas Bri would select the field and just type in '1' then '2' to make '12'. These different approaches caused different results for the example 1 above. Mike's would fail, and Bri's would succeed.

Both example 1 and example 3 helped point out the problem: the value property going into the FormControlTypeNumber component was calling toODOPPrecision() and by removing this call the value property was then updating correctly.

Change from

    <FormControlTypeNumber id={'v_'+this.props.id} disabled={true} value={this.props.value.toODOPPrecision()} />

to

    <FormControlTypeNumber id={'v_'+this.props.id} disabled={true} value={this.props.value} />

Updates made, merged into master, and maybe just maybe we can close this SOB.

**Comment by grumpyinca** [comment]
The Action : Trade : Size modal appears to have a default value that is too small by a factor of 100.

I believe that line 827 of ActionTrade.js: 
`  <FormControlTypeNumber value={this.state.defaultest} onChangeValid={this.onSizeChangeValid} onChangeInvalid={this.onSizeChangeInvalid}/>
`
should get a factor of 100 multiplied in to each of the three arguments to FormControlTypeNumber.

**Comment by 1fifoto** [comment]
Let's talk about this one. added to agenda.

**Comment by 1fifoto** [comment]
Fixed, merged, and closed

**Comment by grumpyinca** [comment]
Oops!  It turns out that the numbers in the Action : Trade : Arbitrary (weight) modal also need to be adjusted by that same factor of 100.

**Comment by 1fifoto** [comment]
Move Item 1 above to a separate issue. Fixed Item 2 above, merged into master, closing.
