### ISSUE TITLE
Repair Client Test Cases to run with Functional Components & Redux Tool Kit

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#922]
The current test cases fail to run. For example, here is one such error

> FAIL  src/__test__/Piston-Cylinder/dispatcher.test.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
> 
>     Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
> 
>     By default "node_modules" folder is ignored by transformers.
> 
>     Here's what you can do:
>      • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
>      • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/configuration
>     For information about custom transformations, see:
>     https://jestjs.io/docs/code-transformation
> 
>     Details:
> 
>     /Users/brianwatt/git/odop/client/node_modules/query-string/index.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as queryString from './base.js';
>                                                                                       ^^^^^^
> 
>     SyntaxError: Cannot use import statement outside a module
> 
>       1 | import runtimeEnv from '@mars/heroku-js-runtime-env';
>     > 2 | import queryString from 'query-string';
>         | ^
>       3 | require('dotenv').config();
>       4 |
>       5 | var node_env;
> 
>       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
>       at Object.<anonymous> (src/config.js:2:1)
>       at Object.<anonymous> (src/store/modelSlice.js:4:1)
>       at Object.<anonymous> (src/__test__/Piston-Cylinder/dispatcher.test.js:7:1)

**Comment by 1fifoto** [comment]
Success:
Test Suites: 28 passed, 28 total
Tests:    115 passed, 115 total
Snapshots:  0 total
Time:    1424.969 s
Ran all test suites.
[3:33](https://thegrumpys.slack.com/archives/CBFGSRWKB/p1725136436263219)
And some performance numbers:
PASS src/__test__/Piston-Cylinder/performance.test.js (136.986 s)
 ● Console
  console.log
   reducers change symbol value 1000000x duration= 113075
   at Object.<anonymous> (src/__test__/Piston-Cylinder/performance.test.js:32:13)
  console.log
   invokeEquationSet 100000x duration= 16696
   at Object.<anonymous> (src/__test__/Piston-Cylinder/performance.test.js:56:13)
  console.log
   search without merit 1000x duration= 7152
   at Object.<anonymous> (src/__test__/Piston-Cylinder/performance.test.js:129:13) (edited) 
[3:35](https://thegrumpys.slack.com/archives/CBFGSRWKB/p1725136517010699)
Summary: the performance is awful. 1424 second is 23 minutes! Whereas in the past it would be done so so much quicker.
[3:36]But the good thing is the tests run successfully especially the Spring demo/tutorial ones (edited)

**Comment by 1fifoto** [comment]
Merged into master, closing
