### ISSUE TITLE
Cannot read properties of undefined (reading 'toPrecision')

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#952]
The following problem(s) are associated with Calculator View of the current v5.1rc1 staging system.

There may be multiple cases that produce a similar traceback.  Some seem to be associated with clicking the Search (solve) button in the Edit Independent / Dependent Variable modal dialog.  While all get a traceback, some cases result in the app becoming unresponsive, some do not.

Steps to produce first case:
1. Load or reset the app (defaults to compression spring, US units)
2. Confirm that the browser developer tools are loaded & console window is visible
3. Select Calculator View
4. Click the value of Force_2 and observe the **Edit Independent Variable Force_2** modal dialog
5. Change the value 39 to 50
6. Click the Search (solve) button in the modal dialog box
7.  Observe traceback similar to:

``` SymbolValue.jsx:126  Uncaught TypeError: Cannot read properties of undefined (reading 'toPrecision')
    at ce (SymbolValue.jsx:126:173)
    at ae (SymbolValue.jsx:97:5)
    at Object.Fe (react-dom.production.min.js:54:317)
    at He (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Li (react-dom.production.min.js:105:68)
    at Pi (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at dc (react-dom.production.min.js:274:42)
    at Ne (react-dom.production.min.js:52:375) 
```

Steps to produce a second case:
1. Load or reset the app (defaults to compression spring, US units)
2. Confirm that the browser developer tools are loaded & console window is visible
3. Select Calculator View
4. _This step is probably not necessary._  Import this design:
[GuidedDesignBaseline2.zip](https://github.com/user-attachments/files/17594169/GuidedDesignBaseline2.zip)
5. In Calc View, select std Wire_Dia 0.034
6. Without leaving the "Edit Independent Variable Wire_Dia" dialog box, click Search (solve). 
7. In console window, observe traceback similar to: 

``` SymbolValueWireDia.jsx:192 
 Uncaught TypeError: Cannot read properties of undefined (reading 'toPrecision')
    at me (SymbolValueWireDia.jsx:192:173)
    at he (SymbolValueWireDia.jsx:162:5)
    at Object.Fe (react-dom.production.min.js:54:317)
    at He (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Li (react-dom.production.min.js:105:68)
    at Pi (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at dc (react-dom.production.min.js:274:42)
    at Ne (react-dom.production.min.js:52:375)
me	@	SymbolValueWireDia.jsx:192
he	@	SymbolValueWireDia.jsx:162
Show 11 more frames 
```

**Comment by 1fifoto** [comment]
Merged into master, closing
