### ISSUE TITLE
Add store import to ResultTable

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#955]
I was making changes in branch 925 (Add more images to variable name tooltips) and noticed that Search fails with a traceback.
Later, I observed the same problem in the master branch (I made no changes there).  The staging system does not fail.
So, this seems very weird because I think that there should be no differences between the current master and staging.
To reproduce the problem:
Load the app in development system master branch (all defaults; Startup = Compression, US units)
Change OD_Free from 1.1 to 1.2
Click Search button
Observe traceback:
Main window traceback
Uncaught runtime errors:
×
ERROR
store is not defined
ReferenceError: store is not defined
    at doSearch (http://localhost:3000/static/js/bundle.js:8440:18)
    at onSearchRequest (http://localhost:3000/static/js/bundle.js:8419:5)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:219557:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:219601:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:219658:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:219672:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:223815:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:223841:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:223852:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:223861:7)
Console window traceback
2
ResultTable.jsx:71 
 Uncaught ReferenceError: store is not defined
    at doSearch (ResultTable.jsx:71:1)
    at onSearchRequest (ResultTable.jsx:46:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
doSearch	@	ResultTable.jsx:71
onSearchRequest	@	ResultTable.jsx:46
Show 15 more frames (edited)

**Comment by 1fifoto** [comment]
Add to top of file.

    import store from "../store/store";

**Comment by 1fifoto** [comment]
Merged into master, closing
