### ISSUE TITLE
"Back" in Execute script produces error message in console

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#966]
Using the "Back" button in an Execute script produces an "Uncaught ReferenceError" error message in the browser console. 
```
Uncaught ReferenceError: next is not defined
    at onClick (ExecutePanel.jsx:119:77)
    at Object.Fe (react-dom.production.min.js:54:317)
    at He (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Li (react-dom.production.min.js:105:68)
    at Pi (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at dc (react-dom.production.min.js:274:42)
    at Ne (react-dom.production.min.js:52:375)
    at Gi (react-dom.production.min.js:109:469)
```
It does not appear to matter which execute script is operating.

### To reproduce:
1. reload ODOP app
2. confirm that the developer tools console is open
3. Run any Action:Execute, demo or tutorial script (for example: increasePrecision)
4. Next
5. Back
6. Observe the above message in the console.  **_<--- This is the bug_**

**Comment by 1fifoto** [comment]
Merged into master, closing
