### ISSUE TITLE
Production V5.1 Fails Heroku build

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/odop#967]
Subset of Heroku build showing error

    remote:    Find out more about deployment here:
    remote:
    remote:     https://cra.link/deployment
    remote:
    remote: /tmp/build_d6e5db36/node_modules/terraform/lib/helpers/memoized.js:4
    remote: var cache  = new Lru({ ttl: 500, max: 2000 })
    remote:        ^
    remote:
    remote: TypeError: Lru is not a constructor
    remote:   at Object.<anonymous> (/tmp/build_d6e5db36/node_modules/terraform/lib/helpers/memoized.js:4:15)
    remote:   at Module._compile (node:internal/modules/cjs/loader:1469:14)
    remote:   at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    remote:   at Module.load (node:internal/modules/cjs/loader:1288:32)
    remote:   at Module._load (node:internal/modules/cjs/loader:1104:12)
    remote:   at Module.require (node:internal/modules/cjs/loader:1311:19)
    remote:   at require (node:internal/modules/helpers:179:18)
    remote:   at Object.<anonymous> (/tmp/build_d6e5db36/node_modules/terraform/lib/helpers/index.js:14:5)
    remote:   at Module._compile (node:internal/modules/cjs/loader:1469:14)
    remote:   at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

**Comment by 1fifoto** [comment]
Master updated, no branch created, closing.
